### ISSUE TITLE
add_precursor_mz filter function

### ISSUE THREAD

**Issue by fdiblen** [matchms/matchms-backup#104]
This issue is only about add_precursor_mz filter.
add_precursor_mz function need more explanation and it should be implemented.
We don't know what this filter does and why it is needed.
Other candidate filters are listed in #75

**Comment by florian-huber** [comment]
That indeed a very confusing part about the MS/MS or MS2 type of data. The input MGF usually will give a 'pepmass' which *should* be the precursor mass. In the past I specifially renamed this to ``precursor_mass`` because that was needed for some other libraries. 

Writing a filter function for a mere renaming seems a bit overkill to me.
In my opinion we could either make the renaming part of the Spectrum init function, or we leave it for now and stick to the already existing "pepmass" field (``spectrum.metadata["pepmass"][0]``).

**Comment by fdiblen** [comment]
We will decide this in future. We are not at the point to decide this yet.

**Comment by fdiblen** [comment]
We decided to keep using spectrum.get("pepmass")[0].
