### ISSUE TITLE
Describe precursor and parent mass in glossary

### ISSUE THREAD

**Issue by sverhoeven** [matchms/matchms-backup#117]

**Comment by fdiblen** [comment]
- Add precursor and parent mass, with definitions, to README.md to close this issue.

**Comment by florian-huber** [comment]
I plan to use this occasion to settle on a consistent way of naming those things. Because in reality, those terms are mixed up all the time, for instance some are used as synonyms although they are not.

I checked with the PI, and suggest to consistently use:

| Name  | variable name | description
| ------------- | ------------- | ------------- |
| precursor m/z   | precursor_mz  | The m/z ratio of the original ion as it is being measured (="pepmass" in MGF file) |
| parent mass   | parent_mass  | The actual mass of the original compound (=  precursor_mz * abs(charge) - charge * proton_mass) |

Precursor mass and parent mass are used interchangeably, but our collaborated prefer using "parent mass" to avoid common confusion with "precursor m/z".

**Comment by florian-huber** [comment]
Added both to readme.

**Comment by sverhoeven** [comment]
Great, thanks
