### ISSUE TITLE
Publish the Python package on pypi

### ISSUE THREAD

**Issue by fdiblen** [matchms/matchms-backup#13]
After closing this issue, Zenodo integration can be enabled.

**Comment by fdiblen** [comment]
Automatic publishing is disabled atm.
To publish the package, secrets for the username and password should be added to the repository settings.
See the following lines in Github actions configuration (.github/workflows/pythonapp.yml).

    #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
    #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

**Comment by jspaaks** [comment]
With ``pip``, users can do conditional installs like
```
pip install <packagename>[key]
```

For example the Python template uses ``dev`` so that users can install the development dependencies like the testing framework, linting and that sort of thing: https://github.com/NLeSC/python-template/blob/2ca5e4291e3006eeed3f4587c8c5d9cc7feb25ce/%7B%7Bcookiecutter.project_slug%7D%7D/setup.py#L69-L71

However, I was thinking, since the installs of in particular ``openbabel`` and ``rdkit`` have been causing so many headaches, we could make them conditional.

This would go nicely with differentiating between preprocessing filters and postprocessing filters, since it is only the postprocessing filters that need ``openbabel`` and ``rdkit``.

We could use a conditional install using ``extras_require`` in ``setup.py`` such that users can do
```
pip install matchms
```
and get the package without its postprocessing ability; or, alternatively,
```
pip install matchms[with_postprocessing]
```
to get the full feature set (as well as its associated problems). This distinction would be especially useful for people who are not interested in using matchms for calculating similarity measures on a list of spectrums, but instead want to do that on say, a list of objects of type ``GeneSequence``.

**Comment by fdiblen** [comment]
> With `pip`, users can do conditional installs like
> 
> ```
> pip install <packagename>[key]
> ```
> 
> For example the Python template uses `dev` so that users can install the development dependencies like the testing framework, linting and that sort of thing: https://github.com/NLeSC/python-template/blob/2ca5e4291e3006eeed3f4587c8c5d9cc7feb25ce/%7B%7Bcookiecutter.project_slug%7D%7D/setup.py#L69-L71
> 
> However, I was thinking, since the installs of in particular `openbabel` and `rdkit` have been causing so many headaches, we could make them conditional.
> 
> This would go nicely with differentiating between preprocessing filters and postprocessing filters, since it is only the postprocessing filters that need `openbabel` and `rdkit`.
> 
> We could use a conditional install using `extras_require` in `setup.py` such that users can do
> 
> ```
> pip install matchms
> ```
> 
> and get the package without its postprocessing ability; or, alternatively,
> 
> ```
> pip install matchms[with_postprocessing]
> ```
> 
> to get the full feature set (as well as its associated problems). This distinction would be especially useful for people who are not interested in using matchms for calculating similarity measures on a list of spectrums, but instead want to do that on say, a list of objects of type `GeneSequence`.

_extras_require_ can only be used for pure python packages. We have some dependencies which are available only in anaconda repos. So nah nah :disappointed: 

We can create a separate package for development which can solve this issue:
conda install matchms-dev

**Comment by fdiblen** [comment]
btw, PR #68 should close this issue because this is only about pushing package to pypi. Maybe we should have this discussion in another issue.

**Comment by jspaaks** [comment]
I've made new issue for conditional install https://github.com/matchms/matchms/issues/81

**Comment by fdiblen** [comment]
PYPI deployment workflow was added in PR #68 but it is not tested yet. We should test it using NLeSC's credentials.

**Comment by sverhoeven** [comment]
For what pypi accounts to use please see https://guide.esciencecenter.nl/best_practices/language_guides/python.html#building-and-packaging-code.
