### ISSUE TITLE
.intensities v .peaks and .losses

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms-backup#138]
Now that we have a filter that can calculate losses based on mz and intensities, we have to make a decision on how we are going to store those data in ``Spectrum``. Currently, we are storing the location of peaks as ``.mz``, and their magnitude as ``.intensities`` (technically those are getters but that doesn't matter for the discussion).

Some options:
1. add a boolean array ``.is_peak``, with the same dimensions as ``.mz`` and ``.intensities``.
    - ``.is_peak``
    - ``.mz``
    - ``.intensities``
1. rename ``.intensities`` to ``.intensity_peaks``, introduce a ``.intensity_losses``, and change ``.mz`` to ``.mz_peaks`` and ``.mz_losses``
   - ``.intensity_peaks``
   - ``.intensity_losses``
   - ``.mz_peaks``
   - ``.mz_losses``
1. rename ``.intensities`` to ``.peaks``, introduce a ``.losses``, and change ``.mz`` to ``.mz_peaks`` and ``.mz_losses``
   - ``.peaks``
   - ``.losses``
   - ``.mz_peaks``
   - ``.mz_losses``
1. rename ``.intensities`` to ``.peaks``, introduce a ``.losses``, and change ``.mz`` to a ``dict`` with keys  ``"peaks"`` and ``"losses"``
   - ``.peaks``
   - ``.losses``
   - ``.mz["peaks"]``
   - ``.mz["losses"]``
1. change ``.intensities`` to ``.peaks`` and change the data type to a list of tuple with ``(mz, intensity)``; add ``.losses`` of data type list of tuple with ``(mz, intensity)``
   - ``.peaks``
   - ``.losses``
1. change the data type of ``intensities`` to a list of tuple with ``(mz, intensity, is_peak)``
   - ``.intensities``
1. change the data type of ``intensities`` to a dict with keys ``"peaks"`` and ``"losses"``; change the data type of ``mz`` to a ``dict`` with keys ``"peaks"`` and ``"losses"``, where ``peaks`` and ``losses`` are of type ``numpy.ndarray`` of ``float``
   - ``.intensities["peaks"]``
   - ``.intensities["losses"]``
   - ``.mz["peaks"]``
   - ``.mz["losses"]``
1. leave ``.intensities`` and ``.mz`` as they are, but introduce a ``.losses`` ``dict`` with its own ``.mz`` and ``.intensities`` arrays
   - ``.intensities``
   - ``.mz``
   - ``.losses["intensities"]``
   - ``.losses["mz"]``
1. leave ``.mz`` as it is, but introduce a sign on ``.intensities``
   - ``.intensities``
   - ``.mz`` (signed)

I'd be happy to read about your opinions.

**Comment by jspaaks** [comment]
or, implement an obnject that stores an array of mz  and an array of intensities, with getters and probably setters, such that you can do
```python
spectrum.peaks.mz
spectrum.peaks.intensities
spectrum.losses.mz
spectrum.losses.intensities
```

**Comment by cwmeijer** [comment]
I prefer the object version with setters and getters. It uses the same structure as with the scores, which is nice. It's also communicates well what the mzs are.

I also like 1. It's simple. Not as elegant as the object version though.

The rest of this comment describes my objections about the other options:

For 2 and 3 there wouldn't be an option to get all intensities and mzs anymore. That's a downside. Storing them as well would be redundant and a bit confusing.

I've used dicts and keywords for the core data structure with laserchicken and I always regretted this. The ide won't be able to help you with checking the keys, it's really messy. So I would vote against 4, 7 and 8 because of this reason.

I think option 9 is not very intuitive because this would mean the intensity isn't accurate for the losses anymore because we need to scale by -1 first in that case (if I understand correctly).

I would go for tuples like in 5 or 6. I don't think individual peaks have enough meaning in our context to pick that approach (but could very much be wrong there). Also, you would have to check what the order of the elements in the tuple are every time. Error prone.

**Comment by jspaaks** [comment]
Good point on autocomplete, hadnt thought about that.

**Comment by jspaaks** [comment]
PR #150
