### ISSUE TITLE
Add integration test

### ISSUE THREAD

**Issue by fdiblen** [matchms/matchms-backup#5]
Add integration test to the generic parts of the software.

**Comment by cwmeijer** [comment]
For some information about currently existing tests see my comment in #4 .

**Comment by jspaaks** [comment]
I think that conceptually, https://github.com/matchms/matchms/issues/57#issuecomment-609700997 is already pretty close to what Chris is saying in [#4](https://github.com/matchms/matchms/issues/4#issuecomment-606637868). In order to use Spec2Vec as a similarity measure, we need to train a model, and for that we need to be able to convert spectrums to sentences.

**Comment by jspaaks** [comment]
Addressed in PR https://github.com/matchms/matchms/pull/89

**Comment by cwmeijer** [comment]
can be closed after merge (#89)
