### ISSUE TITLE
add filtering/expfit function

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms-backup#55]
- [ ] add a harmonization method, with interface

    ```
    expfit(spectrum, threshold=0.01, n_bins=100, n_peaks_min=25)
    ```
    I think this is similar to @florian-huber's ``Spectrum.exp_intensity_filter``. Other parameters such as ``num_bins``, ``min_peaks_for_exp_fit`` are currently not exposed but should also be included in this function. See ``process_peaks`` in ``old-structure/ms_functions``. Overall, ``process_peaks`` needs to be refactored, because it is much too complicated now. Also ``n_bins`` and ``n_peaks_min`` may not be appropriate to guarantee stable fitting behavior, but we can look at that later.
- [ ] add test

**Comment by florian-huber** [comment]
As discussed today with @jspaaks: I think it is good to separate 'harmonization' from 'filtering. There is now sharp boundary, but at least this way we can better take care of meany cleaning steps that most users would not consider to be filtering. @jspaaks suggestions was to still keep it under .filtering (fine with me) but break it down into small, very concrete functions that reflect well that is done to the data. To get an idea what we currently do to the data, here some part of our manuscript methods section:
## "Harmonization"
- Make inchi strings more consistent in style (make strings consistent in style: 'INCHI="InChI=..."'). 
- Detect smiles which were given as inchi and convert those into proper inchi (openbabel).
- Search spectra with inchi but no smiles, or with smiles but no inchi. Convert annotations between smiles and inchi for those cases (openbabel).
- Search for InChI which cannot be read by openbabel.
Those were found to suffer from one of the following:
InChIkeys were given instead of InChI
InChI were incorrect. This is usually due to missing ‘-’ or other minor faults in the given strings.
If inchi are indeed inchikeys AND smiles are known, corrected inchi are produced by conversion of smiles (openbabel).
- For all other ‘defective’ inchi an automated search via Pubchem is performed. 
Potential candidates are first selected by matching compound name, and extended (if necessary) by matches of the compound formula. 
All those candidates are evaluated based on either the inchi or inchikey. A candidate is considered a match if name + inchikey (first 14 letters) or name + simplified inchi (first 3 parts of the inchi + removing problematic characters) are a match.
- Add ionization mode (‘ionmode’ field) if missing and if possible based on adduct notation.
- Add (and correct) signs in charge field to format: “X-” or “X+”.
- Replace weird characters in Title
- interpret charge field (based on charge field string and metadata)
- Derive precursor-mass and parent-mass from pepmass field

## Filtering
- Normalize peak intensities to max intensity peak = 1.
- Filter peaks based on min_mz, max_mz window (optional).
- Filter peaks based on exponential fit to intensitiy histogram (optional).
- Filter peaks based on relative intensity threshold (optional).

**Comment by jspaaks** [comment]
Hi @florian-huber:
For each of the items above, could you annote it with either "preprocessing" or "postprocessing" to indicate whether a filter is necessary for calculating any of the similarity measures?

While you're at it, could you copy/move https://github.com/matchms/matchms/issues/55#issuecomment-608485040 to its own issue (perhaps labeled _Candidate filter functions_ or something), since it is different from _add harmonization/expfit function_.

Thanks!

**Comment by jspaaks** [comment]
I fiddled with exponential fitting for a bit, which resulted in https://github.com/matchms/matchms/pull/108. However, based on the fits & visualizations that I have made to the 50 or so spectrums from [pesticides.mgf](https://github.com/matchms/matchms/blob/92f5dfc786090571d2f26278ea84bf196bbacf83/tests/pesticides.mgf), I'd say we should rethink this method before implementing a filter based on it.
